baseurl = "https://talatera.github.io/"
title = "IASSIST - International Association for Social Science Information Service and Technology "
theme = "hugo-universal-theme"
#themesDir = "../.."
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code: UA-56271826-1 
googleAnalytics = ""

# Define the number of posts per page
paginate = 10

[menu]

# Main menu

[[menu.main]]
    identifier="home"
    name = "Home"
    url  = "/"
    weight = 1
	
[[menu.main]]
    identifier = "about"
    name = "About"
    url  = "/about/about-iassist"
    weight = 2	

[[menu.main]]
    identifier="conferences"
    name = "Conferences"
    url  = "/conferences/conferences"
    weight = 3

[[menu.main]]
    identifier="blog"
    name = "Blog"
    url  = "/blog/"
    weight = 4

[[menu.main]]
    identifier="community"
    name = "Community"
    url  = "/community/"
    weight = 5

[[menu.main]]
    identifier = "resources"
    name = "Resources"
    url = "/resources/"
    weight = 6

[[menu.main]]
    identifier = "contact"
    name = "Contact"
    url  = "/contact/"
    weight = 7

# Top bar social links menu

#[[menu.topbar]]
#    weight = 1
#    name = "GitHub"
#    url = "https://github.com/devcows/hugo-universal-theme"
#    pre = "<i class='fab fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 2
    name = "Facebook"
    url = "http://facebook.com/iassistdata"
    pre = "<i class='fab fa-2x fa-facebook'></i>"

[[menu.topbar]]
    weight = 3
    name = "Twitter"
    url = "http://twitter.com/iassistdata"
    pre = "<i class='fab fa-2x fa-twitter'></i>"

#[[menu.topbar]]
#    weight = 4
#    name = "Email"
#    url = "mailto:your@email.com"
#    pre = "<i class='fas fa-2x fa-envelope'></i>"

[params]
    viewMorePostLink = "/blog/"
    author = "IASSIST"
    defaultKeywords = ["research data", "association", "professional development", "data support", "data science", "community", "iassist quarterly"]
    mainSections = ["blog"]
    defaultDescription = "IASSIST is an international organization of professionals working in and with information technology and data services to support research and teaching in the social sciences and beyond."

    # Social media
    facebook_site = "iassistdata/" # the Facebook handle of your site ('https://www.facebook.com/HANDLE')
    twitter_site = "iassistdata" # the Twitter handle of your site (without the '@')
    default_sharing_image = "img/sharing-default.png"

    # Google Maps API key (if not set will default to not passing a key.)
    googleMapsApiKey = "AIzaSyCFhtWLJcE30xOAjcbSFi-0fnoVmQZPb1Y"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "pink"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io email
    email = "your@email.com"
    contact_form_ajax = false

    about_us = "<p>IASSIST is an international organization of professionals working with information technology and data services to support research and teaching in the social sciences.</p>"
    copyright = "Content licensed by Creative Commons BY 4.0" #Copyright (c) 2015 - 2016, YourCompany; all rights reserved.

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    logo = "img/logo.png"
    logo_small = "img/logo-small.png"
    address = """<p class=""><strong>IASSIST</strong>
        <br><a href="#">&raquo; Officials</a>
        <br><a href="#">&raquo; Membership issues</a>
        <br><a href="#">&raquo; Web team</a>		
        <br><strong></strong>
      </p>
      """
    latitude = "-12.043333"
    longitude = "-77.028333"

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = false
    text = """<p class="hidden-sm hidden-xs">Contact us: iassistdata@gmail.com.</p>
      <p class="hidden-md hidden-lg"><a href="#" data-animate-hover="pulse"><i class="fas fa-phone"></i></a>
      <a href="#" data-animate-hover="pulse"><i class="fas fa-envelope"></i></a>
      </p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carousel]
    enable = true
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.

[params.features]
    enable = true
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.

[params.testimonials]
    enable = false
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README.
    title = "Testimonials"
    subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."

[params.see_more]
    enable = false
    icon = "far fa-file-alt"
    title = "IASSIST on Social Media"
    subtitle = "We have prepared for you more than 40 different HTML pages, including 5 variations of homepage."
    link_url = "#"
    link_text = "Check other homepages"

[params.clients]
    enable = true
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more informtion take a look at the README.
    title = "IASSIST on Social Media"
    subtitle = "Follow us, and get the latest updates as they happen."

[params.recent_posts]
    enable = true
    title = "From iBlog"
    subtitle = "iBlog is IASSIST's own blog. Entries on various topics are written by our members."
	
[markup.goldmark.renderer]
    unsafe= true